### PR TITLE
Ab#5 Arttu commits

### PR DESCRIPTION
**Pull request by Arttu21003**

### CODE REVIEW

**Review by AkuTRTKP21A3 — CHANGES_REQUESTED** [review]
Hhmmmm, that is not how you change the color correctly, please change it!

**Comment by Arttu21003** [comment]
Yes Sir! I will change it immediately.

**Review by AkuTRTKP21A3 — APPROVED** [review]
Thank you, now it looks better! Very good job!

**Review by AkuTRTKP21A3 — APPROVED** [review]
Now it looks better, thank you!

**Pull request merged**
